/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccediRouteImport } from './routes/accedi'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedCategorieRouteImport } from './routes/_authenticated/categorie'
import { Route as AuthenticatedContiRouteImport } from './routes/_authenticated/conti'
import { Route as AuthenticatedEntrateRouteImport } from './routes/_authenticated/entrate'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated/impostazioni'
import { Route as AuthenticatedMovimentiRouteImport } from './routes/_authenticated/movimenti'
import { Route as AuthenticatedObiettiviRouteImport } from './routes/_authenticated/obiettivi'
import { Route as AuthenticatedPannelloRouteImport } from './routes/_authenticated/pannello'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccediRoute = AccediRouteImport.update({
  id: '/accedi',
  path: '/accedi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategorieRoute = AuthenticatedCategorieRouteImport.update({
  id: '/categorie',
  path: '/categorie',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContiRoute = AuthenticatedContiRouteImport.update({
  id: '/conti',
  path: '/conti',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrateRoute = AuthenticatedEntrateRouteImport.update({
  id: '/entrate',
  path: '/entrate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMovimentiRoute = AuthenticatedMovimentiRouteImport.update({
  id: '/movimenti',
  path: '/movimenti',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObiettiviRoute = AuthenticatedObiettiviRouteImport.update({
  id: '/obiettivi',
  path: '/obiettivi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPannelloRoute = AuthenticatedPannelloRouteImport.update({
  id: '/pannello',
  path: '/pannello',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accedi': typeof AccediRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/categorie': typeof AuthenticatedCategorieRoute
  '/conti': typeof AuthenticatedContiRoute
  '/entrate': typeof AuthenticatedEntrateRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/movimenti': typeof AuthenticatedMovimentiRoute
  '/obiettivi': typeof AuthenticatedObiettiviRoute
  '/pannello': typeof AuthenticatedPannelloRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accedi': typeof AccediRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/categorie': typeof AuthenticatedCategorieRoute
  '/conti': typeof AuthenticatedContiRoute
  '/entrate': typeof AuthenticatedEntrateRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/movimenti': typeof AuthenticatedMovimentiRoute
  '/obiettivi': typeof AuthenticatedObiettiviRoute
  '/pannello': typeof AuthenticatedPannelloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accedi': typeof AccediRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/categorie': typeof AuthenticatedCategorieRoute
  '/_authenticated/conti': typeof AuthenticatedContiRoute
  '/_authenticated/entrate': typeof AuthenticatedEntrateRoute
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/_authenticated/movimenti': typeof AuthenticatedMovimentiRoute
  '/_authenticated/obiettivi': typeof AuthenticatedObiettiviRoute
  '/_authenticated/pannello': typeof AuthenticatedPannelloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accedi'
    | '/budget'
    | '/categorie'
    | '/conti'
    | '/entrate'
    | '/impostazioni'
    | '/movimenti'
    | '/obiettivi'
    | '/pannello'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accedi'
    | '/budget'
    | '/categorie'
    | '/conti'
    | '/entrate'
    | '/impostazioni'
    | '/movimenti'
    | '/obiettivi'
    | '/pannello'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accedi'
    | '/_authenticated/budget'
    | '/_authenticated/categorie'
    | '/_authenticated/conti'
    | '/_authenticated/entrate'
    | '/_authenticated/impostazioni'
    | '/_authenticated/movimenti'
    | '/_authenticated/obiettivi'
    | '/_authenticated/pannello'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccediRoute: typeof AccediRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accedi': {
      id: '/accedi'
      path: '/accedi'
      fullPath: '/accedi'
      preLoaderRoute: typeof AccediRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorie': {
      id: '/_authenticated/categorie'
      path: '/categorie'
      fullPath: '/categorie'
      preLoaderRoute: typeof AuthenticatedCategorieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conti': {
      id: '/_authenticated/conti'
      path: '/conti'
      fullPath: '/conti'
      preLoaderRoute: typeof AuthenticatedContiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrate': {
      id: '/_authenticated/entrate'
      path: '/entrate'
      fullPath: '/entrate'
      preLoaderRoute: typeof AuthenticatedEntrateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimenti': {
      id: '/_authenticated/movimenti'
      path: '/movimenti'
      fullPath: '/movimenti'
      preLoaderRoute: typeof AuthenticatedMovimentiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obiettivi': {
      id: '/_authenticated/obiettivi'
      path: '/obiettivi'
      fullPath: '/obiettivi'
      preLoaderRoute: typeof AuthenticatedObiettiviRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pannello': {
      id: '/_authenticated/pannello'
      path: '/pannello'
      fullPath: '/pannello'
      preLoaderRoute: typeof AuthenticatedPannelloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedCategorieRoute: typeof AuthenticatedCategorieRoute
  AuthenticatedContiRoute: typeof AuthenticatedContiRoute
  AuthenticatedEntrateRoute: typeof AuthenticatedEntrateRoute
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRoute
  AuthenticatedMovimentiRoute: typeof AuthenticatedMovimentiRoute
  AuthenticatedObiettiviRoute: typeof AuthenticatedObiettiviRoute
  AuthenticatedPannelloRoute: typeof AuthenticatedPannelloRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedCategorieRoute: AuthenticatedCategorieRoute,
  AuthenticatedContiRoute: AuthenticatedContiRoute,
  AuthenticatedEntrateRoute: AuthenticatedEntrateRoute,
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRoute,
  AuthenticatedMovimentiRoute: AuthenticatedMovimentiRoute,
  AuthenticatedObiettiviRoute: AuthenticatedObiettiviRoute,
  AuthenticatedPannelloRoute: AuthenticatedPannelloRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccediRoute: AccediRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
